### ISSUE TITLE
dnn::readNetFromONNX("./best.onnx");

### ISSUE THREAD

**Issue by never-to-never** [Hexmagic/ONNX-yolov5#3]
Why does “dnn::readNetFromONNX("./best.onnx")”dnn::readNetFromONNX("./best.onnx") report an error when I run test.cpp?

**Comment by Hexmagic** [comment]
there are some ONNX operators OpenCV doesn't implement or not support well.

**Comment by carlosedubarreto** [comment]
Hello @Hexmagic , thanks a lot for the example, and I'm on the second day trying to make it work and I cant find what is the problem (I'm also a newbie on C++)

Using the code you have provided, I keep receiving this error after trying my custom model
![image](https://user-images.githubusercontent.com/4061130/156939325-28f22932-7cfc-47ac-950d-d38b4a28bfbe.png)

Do you have an idea what do I have to do to make it work?
Thanks a lot!

PS.: testing converting the yolov5 models, works great, the problem is when I try to create a custom model.

**Comment by Hexmagic** [comment]
> Hello @Hexmagic , thanks a lot for the example, and I'm on the second day trying to make it work and I cant find what is the problem (I'm also a newbie on C++)
> 
> Using the code you have provided, I keep receiving this error after trying my custom model ![image](https://user-images.githubusercontent.com/4061130/156939325-28f22932-7cfc-47ac-950d-d38b4a28bfbe.png)
> 
> Do you have an idea what do I have to do to make it work? Thanks a lot!
> 
> PS.: testing converting the yolov5 models, works great, the problem is when I try to create a custom model.

can you provide your model link

**Comment by carlosedubarreto** [comment]
sure, here it is.

[2_best.zip](https://github.com/Hexmagic/ONNX-yolov5/files/8195267/2_best.zip)
[3_best.zip](https://github.com/Hexmagic/ONNX-yolov5/files/8195269/3_best.zip)


the 2_best is using an earlier colab code from roboflow
the 3_best is using the latest colab code

I see that both creates different models (I saw it via Neutron) but both gives me the same error.

Now I'm going to try some other things, like the opencv tutorial... But if you could point some direction,, I would thank you a lot.

**Comment by Hexmagic** [comment]
> sure, here it is.
> 
> [2_best.zip](https://github.com/Hexmagic/ONNX-yolov5/files/8195267/2_best.zip) [3_best.zip](https://github.com/Hexmagic/ONNX-yolov5/files/8195269/3_best.zip)
> 
> the 2_best is using an earlier colab code from roboflow the 3_best is using the latest colab code
> 
> I see that both creates different models (I saw it via Neutron) but both gives me the same error.
> 
> Now I'm going to try some other things, like the opencv tutorial... But if you could point some direction,, I would thank you a lot.

Hi [carlosedubarreto](https://github.com/carlosedubarreto), can you provide 3_best.onnx ?I don't know how to convert your pt model to onnx.

**Comment by carlosedubarreto** [comment]
Sure...
I sent both again, because I see they have some substantial differences

BTW, I dont think it is a problem with the code you provided.

[2_best onnx.zip](https://github.com/Hexmagic/ONNX-yolov5/files/8195344/2_best.onnx.zip)
![image](https://user-images.githubusercontent.com/4061130/156980085-c121f132-5ab4-4790-98e9-eca8366820b4.png)




[3_best onnx.zip](https://github.com/Hexmagic/ONNX-yolov5/files/8195349/3_best.onnx.zip)
![image](https://user-images.githubusercontent.com/4061130/156980107-33128b08-21fe-47ad-a72e-915a04be94a0.png)

**Comment by Hexmagic** [comment]
yolov5 origin output shape is 1x25200x85, and your output is 1x25200x14. in  method `postProcess`
```
Mat confs = out.row(r).colRange(5, 85);
```
will cause index out-of-range error, I have updated my code to adapt different class nums. If you want special different class name, change `data/coco.names` content

**Comment by carlosedubarreto** [comment]
Oh, thanks a lot, I'm going to try it.
It makes more sense now that you've explained 😊

**Comment by carlosedubarreto** [comment]
That´s amazing @Hexmagic !!!!!!!!!!!!
It worked!!!!!!

Thank you a lot!!!!!!!!!!!
here is an example of the result
![image](https://user-images.githubusercontent.com/4061130/156989262-9b90fa2f-581c-46d4-aa84-b3bed8db5a79.png)
